# This is a basic workflow to help you get started with Actions

name: Stage the app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [ labeled ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # When someone applies a "stage" label to a pull request, that'll be our indicator that we'd like to deploy our application to a staging environment.
    if: contains(github.event.pull_request.labels.*.name, 'stage')
 

